"""initial migration

Revision ID: 1c397b0a81fd
Revises: 
Create Date: 2022-12-28 12:49:53.967201

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import table, column

from tgbot.misc.constants import channels

# revision identifiers, used by Alembic.
revision = '1c397b0a81fd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=50), nullable=True),
    sa.Column('description', sa.VARCHAR(length=800), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('photo_link', sa.VARCHAR(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('telegram_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=200), nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=200), server_default=sa.text('NULL'), nullable=True),
    sa.Column('username', sa.VARCHAR(length=200), server_default=sa.text('NULL'), nullable=True),
    sa.Column('role', sa.VARCHAR(length=20), nullable=False),
    sa.Column('language', sa.VARCHAR(length=50), nullable=True),
    sa.Column('bonus_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('balance', sa.Integer(), nullable=True),
    sa.Column('referrer_id', sa.BIGINT(), nullable=True),
    sa.ForeignKeyConstraint(['referrer_id'], ['users.telegram_id'], name='FK__users_referrer_id', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('telegram_id')
    )

    op.execute(table('users',
                     sa.Column('telegram_id', sa.BIGINT(), autoincrement=False, nullable=False),
                     sa.Column('first_name', sa.VARCHAR(length=200), nullable=False),
                     sa.Column('role', sa.VARCHAR(length=20), nullable=False),
                     sa.Column('language', sa.VARCHAR(length=50), nullable=True),
                     ).insert().values(telegram_id=int(channels[0]), first_name='Channel', role='Channel', language='uk'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('items')
    # ### end Alembic commands ###
